### ISSUE TITLE
Request: Add ptpimg as an image host

### ISSUE THREAD

**Issue by cubix-netizen** [plotski/upsies#2]
I personally use ptpimg for my bB uploads and would love to have it as a supported image host alongside imgbox.

**Comment by plotski** [comment]
I don't have an account on ptpimg. If the API isn't too complex and you can get
me the documentation, I can try to add support for it. As a last resort, I could
try to extract the implementation from pythonBits.

**Comment by plotski** [comment]
I've added ptpimg support. Getting the API key is not very user friendly for
now. You have to extract it from the HTML form. I'll try to find a good way to
automate that.

But uploading works. This should be all you need to do:

    $ upsies set trackers.bb.image_host ptpimg
    $ upsies set imghosts.ptpimg.apikey flim-flam

**Comment by cubix-netizen** [comment]
Thank you so much plotski!
